version: "3"

services:
  nginx-proxy:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  grafana:
    image: grafana/grafana:8.3.3
    volumes:
      - ./grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:v2.31.1
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
    depends_on:
      - procima

  procima:
    build:
      context: ./procima
      dockerfile: Dockerfile
    container_name: procima
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 10G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    tty: true
    networks:
      - monitoring
    restart: always

networks:
  monitoring:
    driver: bridge